- name: Check Free Space on Virtual HDD
  hosts: windows
  gather_facts: no
  tasks:

    - name: Get Disk Space Info in GB
      win_shell: |
        Get-PSDrive -PSProvider FileSystem | 
        Select-Object Name, 
          @{Name="Used_GB"; Expression={[math]::Round($_.Used / 1GB, 2)}}, 
          @{Name="Free_GB"; Expression={[math]::Round($_.Free / 1GB, 2)}}, 
          @{Name="Total_GB"; Expression={[math]::Round(($_.Used + $_.Free) / 1GB, 2)}} | 
        ConvertTo-Json
      register: disk_info

    - name: Display Retrieved Disk Info
      debug:
        var: disk_info.stdout

    - name: Write Disk Space Info to Report File
      win_shell: |
        $content = @'
        Disk Space Report:
        {{ disk_info.stdout }}
        '@
        $content | Out-File -FilePath C:\DiskSpaceReport.txt -Encoding utf8
      args:
        executable: powershell.exe

    - name: Verify Report File Creation
      win_stat:
        path: C:\DiskSpaceReport.txt
      register: file_status

    - name: Debug Report File Status
      debug:
        var: file_status.stat.exists

