--- 
- name: Windows Update
  hosts: windows
  gather_facts: no
  vars:
    update_max_runtime: 7200 # 2 jam
    reboot_timeout: 3600     # 1 jam

  tasks:
    - name: Ensure Windows Update Service is Running
      ansible.windows.win_service:
        name: wuauserv
        start_mode: manual
        state: started

    - name: Install Updates
      ansible.windows.win_updates:
        category_names: '*'
        state: installed
        reboot: no
      async: "{{ update_max_runtime }}"
      poll: 30
      register: update_result_1

    - name: Reboot
      ansible.windows.win_reboot:
        reboot_timeout: "{{ reboot_timeout }}"

    - name: Check for Leftover Updates
      ansible.windows.win_updates:
        category_names: '*'
        state: installed
        reboot: no
      async: "{{ update_max_runtime }}"
      poll: 30
      register: update_result_2
      when: >
        update_result_1.found_update_count | default(0) > 0 or
        update_result_1.reboot_required | default(false)

    - name: Reboot
      ansible.windows.win_reboot:
        reboot_timeout: "{{ reboot_timeout }}"
      when: 
        - update_result_2 is not skipped

    - name: Force Windows Update UI Refresh
      ansible.windows.win_shell: |
        usoclient StartInteractiveScan
      changed_when: false
      ignore_errors: yes

    - name: Wait for UI Sync
      ansible.builtin.pause:
        seconds: 10

    - name: Stop Windows Update Service
      ansible.windows.win_service:
        name: wuauserv
        state: stopped

    - name: Final Update Report
      debug:
        msg:
          - "=========================================="
          - "Host: {{ inventory_hostname }}"
          - "Phase 1 Installed: {{ update_result_1.installed_update_count | default(0) }}"
          - "Phase 1 Rebooted: {{ update_result_1.reboot_required | default(false) }}"
          - "Phase 2 Installed: {{ update_result_2.installed_update_count | default(0) }}"
          - "=========================================="
