 ---
- name: Save & Clear Windows Event Logs (Optimized)
  hosts: windows
  gather_facts: no
  vars:
    today_ddmmyyyy: "{{ '%d-%m-%Y' | strftime }}"
    dated_path: 'C:\Kalibrasi\{{ today_ddmmyyyy }}'
    log_names:
      - Application
      - Security
      - System
      - Setup

  tasks:
    - name: Ensure log directory exists
      ansible.windows.win_file:
        path: "{{ dated_path }}"
        state: directory

    - name: Get event log counts before clearing (grouped arrays)
      ansible.windows.win_shell: |
        $logs = @('Application','Security','System','Setup')
        $logNames = @()
        $eventCounts = @()

        foreach ($log in $logs) {
          $logNames += $log
          $eventCounts += (Get-WinEvent -ListLog $log).RecordCount
        }

        # Kembalikan satu objek dengan dua properti berupa array
        $obj = [PSCustomObject]@{
          LogName    = $logNames
          EventCount = $eventCounts
        }
        $obj | ConvertTo-Json -Compress
      register: log_counts_grouped_json

    # Debug agar tampil sebagai dua objek (LogName & EventCount)
    - name: Display Event Log Counts (parsed, two objects)
      debug:
        msg:
          - LogName: "{{ (log_counts_grouped_json.stdout | from_json).LogName }}"
          - EventCount: "{{ (log_counts_grouped_json.stdout | from_json).EventCount }}"

    - name: Export event logs to EVTX
      ansible.windows.win_shell: >
        wevtutil.exe epl "{{ item }}" "{{ dated_path }}\{{ item }}.evtx" /ow:true
      loop: "{{ log_names }}"

    - name: Clear each Windows log
      ansible.windows.win_shell: >
        wevtutil cl "{{ item }}"
      loop: "{{ log_names }}"
