---
- name: Save & Clear Windows Event Logs
  hosts: windows
  gather_facts: no
  vars:
    log_dir: 'C:\Users\vagrant\Documents'

  tasks:
    - name: Ensure log directory exists
      ansible.windows.win_file:
        path: "{{ log_dir }}"
        state: directory

    - name: Export Application event log to EVTX
      ansible.windows.win_shell: wevtutil.exe epl Application "{{ log_dir }}\Application.evtx"

    - name: Export Security event log to EVTX
      ansible.windows.win_shell: wevtutil.exe epl Security "{{ log_dir }}\Security.evtx"

    - name: Export System event log to EVTX
      ansible.windows.win_shell: wevtutil.exe epl System "{{ log_dir }}\System.evtx"

    - name: Export Setup event log to EVTX
      ansible.windows.win_shell: wevtutil.exe epl Setup "{{ log_dir }}\Setup.evtx"

    - name: Clear each Windows log
      win_shell: wevtutil cl "{{ item }}"
      loop:
        - Application
        - Security
        - System
        - Setup
