---
- name: Save & Clear Windows Event Logs (Optimized)
  hosts: windows
  gather_facts: no
  vars:
    today_ddmmyyyy: "{{ '%d-%m-%Y' | strftime }}"
    dated_path: 'C:\Kalibrasi\{{ today_ddmmyyyy }}'
    log_names:
      - Application
      - Security
      - System
      - Setup

  tasks:
    - name: Ensure log directory exists
      ansible.windows.win_file:
        path: "{{ dated_path }}"
        state: directory

    - name: Get event log counts before clearing (fast)
      ansible.windows.win_shell: |
        $logs = @('Application','Security','System','Setup')
        $results = @()
        foreach ($log in $logs) {
          $count = (Get-WinEvent -ListLog $log).RecordCount
          $results += [PSCustomObject]@{
            LogName = $log
            EventCount = $count
          }
        }
        $results | ConvertTo-Json
      register: log_counts_json

    - name: Display Event Log Counts (parsed)
      debug:
        msg: "{{ log_counts_json.stdout | from_json }}"

    - name: Export event logs to EVTX
      ansible.windows.win_shell: >
        wevtutil.exe epl "{{ item }}" "{{ dated_path }}\{{ item }}.evtx" /ow:true
      loop: "{{ log_names }}"

    - name: Clear each Windows log
      ansible.windows.win_shell: >
        wevtutil cl "{{ item }}"
      loop: "{{ log_names }}"
